### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by thesismonkey** [ClaudiaBrauer/A-very-short-introduction-to-R#1]
Where it says 

`| Some people prefer te use <- instead of =. They do the same thing. <- consists of two
| characters, namely < and -, and represents an arrow pointing at the object receiving
| the value of the expression.`

"te" should be "to"

**Comment by ClaudiaBrauer** [comment]
Thanks! I finally got around to changing it and I uploaded a new version of the document.
