### ISSUE TITLE
Correction in Module 2 of swirl course

### ISSUE THREAD

**Issue by ghost** [ClaudiaBrauer/A-very-short-introduction-to-R#2]
During the start of the module, there is a error in the description -
```
| Before you start working, you should set your working
| directory to where all your data and script files are or
| should be stored. Within RStudio you can go to 'Tools'>
| 'Set working directory'. Please do this now.
```

It should be `'Session' > 'Set Working Directory'`

**Comment by ClaudiaBrauer** [comment]
Thanks for pointing it out! I changed it already some time ago in the pdf version of "A (very) short introduction to R" and I finally managed to change it in swirl. 

I uploaded a new version to this github site. It will hopefully be updated on the Swirl Course Network site soon too, so you can download the new version automatically.
