### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by retaoliveira** [ClaudiaBrauer/A-very-short-introduction-to-R#5]
Claudia, 

Your tutorial is awesome! Thank you for sharing! I'll get my students to learn with them. 

I'm not a native speaker, but I guess there is a little word missing in the statement at 73% of the course. 

"Within the brackets you specify the arguments. Arguments give extra information to the function. In this case, the argument x says of which set of numbers (vector) the mean **should computed** (namely of B). Sometimes, the name of the argument is not necessary; mean(B) works as well. Try it."

I guess it should've been  **should be computed**. Just a minor contribution! 

Thank you again! 
Renata

**Comment by ClaudiaBrauer** [comment]
Hi Renata,

I'm glad the R intro is useful!

Thanks for pointing out that typo. I finally made time to correct is and some other things and upload a new version. The swirl version is also updated.

Claudia
