### ISSUE TITLE
Dtae for first calculation - change to "current year"

### ISSUE THREAD

**Issue by KenSaville** [ClaudiaBrauer/A-very-short-introduction-to-R#7]
I'm starting to test this out for possible use in my class.  Thanks for putting it together.

Tearlyon there is a quick math problem to calculate % spent at university.  The year is 2019.  Althoug obvious enough,perhaps chage to "use current year" instead of 2019

**Comment by ClaudiaBrauer** [comment]
Thanks! I changed it in the new version.
