### ISSUE TITLE
Freeware Term Conflation

### ISSUE THREAD

**Issue by CMDR-Shrine** [ClaudiaBrauer/A-very-short-introduction-to-R#8]
---
**Issue**

You have made an excellent document and repo that introduces people quickly to R.

However, I did notice the repeated use of the term 'freeware'. In reality, R is FOSS, and all instances of the term "freeware" should be replaced with "FOSS" (Free and Open Source Software) to maintain a up to date summary.

In short, calling R 'freeware' is not representative nor respectful to the R project.

I shall dive into the specifics of exactly why this distinction is important:

---

**Definitions**

*Freeware*

This term typically refers to software that is available for free but does not necessarily grant users the freedom to modify, share, or redistribute the source code. Freeware often comes with restrictions on usage and distribution and is rarely open source, let alone FOSS. It is now an outdated term from the 80s/90s with a negative connotation.

Source: [Wikipedia - Freeware](https://en.wikipedia.org/wiki/Freeware)

*Free and Open Source Software (FOSS)*

R falls under this category. It is released under the GNU General Public License (GPL), which is a widely used free software license. This license guarantees end users the freedom to run, study, share, and modify the software.

Source: [Wikipedia - GNU General Public License](https://en.wikipedia.org/wiki/GNU_General_Public_License)

---

Thank you for your time and efforts to maintain this repo!

**Comment by ClaudiaBrauer** [comment]
Thank you very much for pointing it out and the explanation! I changed it everywhere and uploaded new versions. 

And thanks for the compliments =)

**Comment by CMDR-Shrine** [comment]
Excellent job, thank you for addressing this so quickly!
